### ISSUE TITLE
No connect tox-prpl v0.4.2 latest tox core, Pidgin 2.10.11 linux

### ISSUE THREAD

**Issue by mkolchin** [jin-eld/tox-prpl#36]
(13:48:39) connection: Connecting. gc = 0x8f01b60
(13:48:39) toxprpl: logging in...
(13:48:39) toxprpl: initialized tox callbacks
(13:48:39) toxprpl: logging in Mikhail
(13:48:39) toxprpl: found existing account data
(13:48:39) toxprpl: Will connect to 192.254.75.98:33445 (951C88B7E75C867418ACDB5D273821372BB5BD652740BCDF623A4FA293E75D2F)
(13:48:39) toxprpl: got 2 friends
(13:48:39) toxprpl: added messenger timer as 3265
(13:48:39) toxprpl: added connection timer as 3267
(13:48:44) util: Writing file accounts.xml to directory /home/mikhail/.config/purple
(13:48:44) util: Writing file /home/mikhail/.config/purple/accounts.xml

**Comment by cdobrich** [comment]
I'm having the same problems. Tried using ProjectTox-Core and the regular program.

On Linux. Tox-prpl 0.4.2. Pidgin 2.10.11 (manually compiled myself).

Output from the Pidgin Debug window.
(16:33:26) jabber: jabber_actions: have pep: NO
(16:33:26) account: Connecting to account AltD.
(16:33:26) connection: Connecting. gc = 0x1307fa0
(16:33:26) toxprpl: logging in...
(16:33:26) toxprpl: initialized tox callbacks
(16:33:26) toxprpl: logging in AltD
(16:33:26) toxprpl: found existing account data
(16:33:26) toxprpl: Will connect to 192.254.75.98:33445 (951C88B7E75C867418ACDB5D273821372BB5BD652740BDDF633A4FA193E35D3F)
(16:33:26) toxprpl: added messenger timer as 6712
(16:33:26) toxprpl: added connection timer as 6714
(16:33:26) util: Writing file prefs.xml to directory /home/user/.purple
(16:33:26) util: Writing file /home/user/.purple/prefs.xml

**Comment by mihav** [comment]
the problem is with server port setting - tox-prpl-git does not obbey it - tcpdump clearly shows it's going to the wrong port (42370 instead of 33445, 47873 instead of 443, 15629 instead of 3389): 

(00:07:33) toxprpl: Will connect to y.y.y.y:443 (server-id)
00:07:33.394791 IP x.x.x.x.42495 > y.y.y.y.47873: Flags [S], seq 3715634947, win 29200, options [mss 1460,sackOK,TS val 130694887 ecr 0,nop,wscale 7], length 0
(00:08:03) toxprpl: Will connect to y.y.y.y:33445 (server-id)
00:08:03.231209 IP x.x.x.x.39621 > y.y.y.y.42370: Flags [S], seq 640063411, win 29200, options [mss 1460,sackOK,TS val 130703838 ecr 0,nop,wscale 7], length 0
(00:08:33) toxprpl: Will connect to y.y.y.y:3389 (server-id)
00:08:33.387248 IP x.x.x.x.48250 > y.y.y.y.15629: Flags [S], seq 803986653, win 29200, options [mss 1460,sackOK,TS val 130712885 ecr 0,nop,wscale 7], length 0

it *sometimes* works, because it bootstraps itself from other peers on local networks:
00:27:01.559944 IP6 fe80::x:x:x:x.33445 > ff02::1.33445: UDP, length 33
00:27:01.559960 IP x.x.x.x.33445 > 255.255.255.255.33445: UDP, length 33

tested on 64bit arch linux with latest pidgin, latest tox-git and latest tox-prpl-git

**Comment by rsm-imap-cc** [comment]
I'm having the same problem on Debian Wheezy with the version v0.4.2. It doesn't conects until I start another Tox client. Pidgin version 2.10.10-1~deb7u1. I compiled the plugin my self.

Here is the output of the debug window from pidgin:

(19:55:18) jabber: Sending (ssl) (rsm@imap.cc/24b22fddfd4b3af1235dec3705c18be2f111c026): <iq type='get' id='purple540ecfe6'><ping xmlns='urn:xmpp:ping'/></iq>
(19:55:18) jabber: Recv (ssl)(102): <iq id="purple540ecfe6" type="result"  to='rsm@imap.cc/24b22fddfd4b3af1235dec3705c18be2f111c026'></iq>
(19:55:40) jabber: jabber_actions: have pep: NO
(19:55:40) gtkutils: gdk_pixbuf_new_from_file() returned nothing for file /usr/share/pixmaps/pidgin/protocols/16/tox.png: Failed to open file '/usr/share/pixmaps/pidgin/protocols/16/tox.png': No such file or directory
(19:55:40) toxprpl: setting up account actions
(19:55:40) toxprpl: DHT connected!
(19:55:40) toxprpl: toxprpl_query_buddy_info
(19:55:40) toxprpl: Setting user status for user 58a81006cfd58291ca874c6a4576d5c71ed36ebf101d6526e2302c3ad12bf775 to tox_away
(19:55:40) blist: Updating buddy status for 58a81006cfd58291ca874c6a4576d5c71ed36ebf101d6526e2302c3ad12bf775 (Tox)
(19:55:40) g_log: purple_status_is_online: assertion `status != NULL' failed
(19:55:40) gtkutils: gdk_pixbuf_new_from_file() returned nothing for file /usr/share/pixmaps/pidgin/protocols/16/tox.png: Failed to open file '/usr/share/pixmaps/pidgin/protocols/16/tox.png': No such file or directory
(19:55:40) toxprpl: (re)setting status
(19:55:40) toxprpl: setting status tox_away

I hope it helps.

**Comment by mihav** [comment]
I've created a workaround on tox bootstrap node to redirect above 3 ports to 33445.
Enter this settings under Advanced tab:
Server: 194.249.212.109
Port: 33445
Server key: 3CEE1F054081E7A011234883BC4FC39F661A55B73637A5AC293DDF1251D9432B

**Comment by rsm-imap-cc** [comment]
Yep, it works. 

Thanks!

**Comment by redyoshi49q** [comment]
As can be seen by the issue reference, the workaround node also works for me.  Again, thanks!

**Comment by xenos1984** [comment]
Looks like there is an erroneous call to "htons" here:
https://github.com/jin-eld/tox-prpl/blob/master/src/toxprpl.c#L1059
If I replace htons(port) by port, it connects to the correct port.

**Comment by cdobrich** [comment]
I'm not sure if this issue still needs addressing, because I still had to do the workaround from mihav https://github.com/jin-eld/tox-prpl/issues/36#issuecomment-75612106.

However I finally got Tox to work with Pidgin by using the correct version of Tox-Core (version 0.4.2 before they changed the API) and the latest tox-prpl from jin-eld with the fix for the hton problem back in February.

**Comment by jin-eld** [comment]
On Tue, Apr 14, 2015 at 05:15:20PM -0700, cdobrich wrote:
> I'm not sure if this issue still needs addressing, because I still had to do
> the workaround from mihav #36 (comment).
> 
> However I finally got Tox to work with Pidgin by using the correct version of
> Tox-Core (version 0.4.2 before they changed the API) and the latest tox-prpl
> from jin-eld with the fix for the hton problem back in February.

Yeah.. well sorry bout that, I am only about half through converting
the current code to the new API, I don't think that I am missing much,
mostly the file sending is left and I have yet to understand how it works.

But an update is coming, I promise :)
